/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\scene.gltf -k 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
export function Office(props) {
  const { nodes, materials } = useGLTF("models/plainRoom.gltf");
  // const texture = useTexture("textures/PlainBaked.jpg");
  // texture.flipY = false;
  // texture.encoding = THREE.sRGBEncoding;
  // const textureMaterial = new THREE.MeshStandardMaterial({ map: texture });
  return (
    <group {...props} dispose={null}>
      <group
        name="Dumbbell"
        position={[-2.329, 0.218, 0]}
        rotation={[-Math.PI, 1.439, -Math.PI]}
      >
        <group
          name="Dumbell1"
          position={[-0.321, -0.054, -0.594]}
          rotation={[0.729, -0.138, -3.067]}
        >
          <mesh
            name="Dumbell1_1"
            geometry={nodes.Dumbell1_1.geometry}
            material={materials.IronDumbell1}
          />
          <mesh
            name="Dumbell1_2"
            geometry={nodes.Dumbell1_2.geometry}
            material={materials.SteelDumbell1}
          />
        </group>
      </group>
      <group name="Flute" position={[-0.414, 1.544, -2.916]}>
        <group name="Flute1" rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            name="Flute1_1"
            geometry={nodes.Flute1_1.geometry}
            material={materials.Wood1Flute1}
          />
          <mesh
            name="Flute1_2"
            geometry={nodes.Flute1_2.geometry}
            material={materials.Wood2Flute1}
          />
        </group>
      </group>
      <group
        name="Dumbbell001"
        position={[-2.329, 0.218, 2.284]}
        rotation={[-Math.PI, 1.439, -Math.PI]}
      >
        <group
          name="Dumbell1001"
          position={[0.053, -0.054, -0.63]}
          rotation={[0.7, -0.054, 3.106]}
        >
          <mesh
            name="Dumbell1001_1"
            geometry={nodes.Dumbell1001_1.geometry}
            material={materials["IronDumbell1.001"]}
          />
          <mesh
            name="Dumbell1001_2"
            geometry={nodes.Dumbell1001_2.geometry}
            material={materials["SteelDumbell1.001"]}
          />
        </group>
      </group>
      <group
        name="Dumbbell002"
        position={[-2.329, 0.218, 1.451]}
        rotation={[-Math.PI, 1.439, -Math.PI]}
      >
        <group
          name="Dumbell1002"
          position={[-0.489, -0.054, -0.262]}
          rotation={[0.7, -0.054, 3.106]}
        >
          <mesh
            name="Dumbell1002_1"
            geometry={nodes.Dumbell1002_1.geometry}
            material={materials["IronDumbell1.002"]}
          />
          <mesh
            name="Dumbell1002_2"
            geometry={nodes.Dumbell1002_2.geometry}
            material={materials["SteelDumbell1.002"]}
          />
        </group>
      </group>
      <group
        name="RootNode"
        position={[0, 0.003, -2.413]}
        scale={[3.266, 3.428, 2.742]}
      >
        <mesh
          name="Desk"
          geometry={nodes.Desk.geometry}
          material={materials["Material.006"]}
          scale={100}
        />
      </group>
      <group
        name="RootNode001"
        position={[-3.183, 0.131, -2.54]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={0.753}
      >
        <group name="Door_9" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            name="Door_9_1"
            geometry={nodes.Door_9_1.geometry}
            material={materials["White.001"]}
          />
          <mesh
            name="Door_9_2"
            geometry={nodes.Door_9_2.geometry}
            material={materials["Metal.001"]}
          />
        </group>
      </group>
      <mesh
        name="Hanger"
        geometry={nodes.Hanger.geometry}
        material={materials["Solid.149"]}
        position={[-1.99, 3.014, -3.069]}
      />
      <group
        name="Rabbit"
        position={[2.598, 1.515, -2.945]}
        rotation={[1.592, -0.022, 1.803]}
      >
        <mesh
          name="pCube73_1"
          geometry={nodes.pCube73_1.geometry}
          material={materials.blinn6SG}
        />
        <mesh
          name="pCube73_1_1"
          geometry={nodes.pCube73_1_1.geometry}
          material={materials.blinn5SG}
        />
      </group>
      <group
        name="Tubelight"
        position={[-3.37, 3.513, -0.953]}
        rotation={[Math.PI, -1.565, Math.PI]}
      >
        <mesh
          name="Mesh104_Group4_Model_1"
          geometry={nodes.Mesh104_Group4_Model_1.geometry}
          material={materials.Color_C06}
        />
        <mesh
          name="Mesh104_Group4_Model_1_1"
          geometry={nodes.Mesh104_Group4_Model_1_1.geometry}
          material={materials.Color_007}
        />
        <mesh
          name="Mesh104_Group4_Model_1_2"
          geometry={nodes.Mesh104_Group4_Model_1_2.geometry}
          material={materials.Color_002}
        />
        <mesh
          name="Mesh104_Group4_Model_1_3"
          geometry={nodes.Mesh104_Group4_Model_1_3.geometry}
          material={materials.Translucent_Glass_Blue}
        />
        <mesh
          name="Mesh104_Group4_Model_1_4"
          geometry={nodes.Mesh104_Group4_Model_1_4.geometry}
          material={materials.Color_M08}
        />
      </group>
      <group
        name="books"
        position={[1.436, 2.831, -2.945]}
        rotation={[-Math.PI, 0.103, -Math.PI]}
      >
        <mesh
          name="books_2"
          geometry={nodes.books_2.geometry}
          material={materials.carpetDarker}
        />
        <mesh
          name="books_2_1"
          geometry={nodes.books_2_1.geometry}
          material={materials.carpetWhite}
        />
        <mesh
          name="books_2_2"
          geometry={nodes.books_2_2.geometry}
          material={materials.plant}
        />
        <mesh
          name="books_2_3"
          geometry={nodes.books_2_3.geometry}
          material={materials.metal}
        />
      </group>
      <group
        name="Windows"
        position={[-3.213, 1.979, 0.279]}
        rotation={[-Math.PI, 1.551, -Math.PI]}
      >
        <mesh
          name="mesh1997263557"
          geometry={nodes.mesh1997263557.geometry}
          material={materials.mat15}
        />
        <mesh
          name="mesh1997263557_1"
          geometry={nodes.mesh1997263557_1.geometry}
          material={materials.mat22}
        />
        <mesh
          name="mesh1997263557_2"
          geometry={nodes.mesh1997263557_2.geometry}
          material={materials.mat21}
        />
        <mesh
          name="mesh1997263557_3"
          geometry={nodes.mesh1997263557_3.geometry}
          material={materials.mat23}
        />
        <mesh
          name="mesh1997263557_4"
          geometry={nodes.mesh1997263557_4.geometry}
          material={materials.mat24}
        />
      </group>
      <mesh
        name="BeanBag"
        geometry={nodes.BeanBag.geometry}
        material={materials.Bean_Bag}
        position={[-1.74, 0.326, -2.688]}
      />
      <group
        name="Shelff"
        position={[1.546, 2.563, -2.816]}
        rotation={[0, -1.528, 0]}
      >
        <mesh
          name="Cube-Mesh"
          geometry={nodes["Cube-Mesh"].geometry}
          material={materials.Top}
        />
        <mesh
          name="Cube-Mesh_1"
          geometry={nodes["Cube-Mesh_1"].geometry}
          material={materials.Supports}
        />
      </group>
      <group
        name="Chair"
        position={[1, 0.387, -0.6]}
        rotation={[Math.PI, -0.015, Math.PI]}
      >
        <mesh
          name="Node-Mesh001"
          geometry={nodes["Node-Mesh001"].geometry}
          material={materials.Executive}
        />
        <mesh
          name="Node-Mesh001_1"
          geometry={nodes["Node-Mesh001_1"].geometry}
          material={materials.Executive__1}
        />
        <mesh
          name="Node-Mesh001_2"
          geometry={nodes["Node-Mesh001_2"].geometry}
          material={materials.Executive__2}
        />
        <mesh
          name="Node-Mesh001_3"
          geometry={nodes["Node-Mesh001_3"].geometry}
          material={materials.Executive__3}
        />
      </group>
      <group
        name="LapTop_Cube002"
        position={[1.32, 1.605, -1.701]}
        scale={[1.4, 1.4, 1.1]}
        rotation={[0, -1.459, 0]}
      >
        <mesh
          name="LapTop_Cube002-Mesh"
          geometry={nodes["LapTop_Cube002-Mesh"].geometry}
          material={materials.DarkGray}
        />
        <mesh
          name="LapTop_Cube002-Mesh_1"
          geometry={nodes["LapTop_Cube002-Mesh_1"].geometry}
          material={materials.lighterGray}
        />
        <mesh
          name="LapTop_Cube002-Mesh_2"
          geometry={nodes["LapTop_Cube002-Mesh_2"].geometry}
          material={materials.Gray2}
        />
        <mesh
          name="LapTop_Cube002-Mesh_3"
          geometry={nodes["LapTop_Cube002-Mesh_3"].geometry}
          material={materials.Screen}
        />
      </group>
      <mesh
        name="misc_kettle_cover_Cylinder018"
        geometry={nodes.misc_kettle_cover_Cylinder018.geometry}
        material={materials["Solid.001"]}
        position={[-0.195, 1.62, -2.602]}
        scale={0.062}
      />
      <mesh
        name="misc_kettle_nozzle_Cylinder019"
        geometry={nodes.misc_kettle_nozzle_Cylinder019.geometry}
        material={materials["Solid.001"]}
        position={[-0.195, 1.62, -2.602]}
        scale={0.062}
      />
      <mesh
        name="misc_kettle_Cylinder017"
        geometry={nodes.misc_kettle_Cylinder017.geometry}
        material={materials["Solid.001"]}
        position={[-0.195, 1.62, -2.602]}
        scale={0.062}
      />
      <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={materials["Material.008"]}
        position={[0, 0.015, 0]}
        scale={3.254}
      />
      <mesh
        name="Light"
        geometry={nodes.Light.geometry}
        material={materials["Mat.001"]}
        position={[-1.045, 3.248, -3.306]}
        rotation={[-0.942, -1.506, -3.053]}
        scale={0.013}
      />
      <group
        name="Node"
        position={[-3.221, 2.591, 1.941]}
        rotation={[0, -1.566, 0]}
        scale={0.71}
      >
        <mesh
          name="Node-Mesh002"
          geometry={nodes["Node-Mesh002"].geometry}
          material={materials["mat23.001"]}
        />
        <mesh
          name="Node-Mesh002_1"
          geometry={nodes["Node-Mesh002_1"].geometry}
          material={materials["mat21.001"]}
        />
        <mesh
          name="Node-Mesh002_2"
          geometry={nodes["Node-Mesh002_2"].geometry}
          material={materials["mat15.001"]}
        />
        <mesh
          name="Node-Mesh002_3"
          geometry={nodes["Node-Mesh002_3"].geometry}
          material={materials["mat24.001"]}
        />
        <mesh
          name="Node-Mesh002_4"
          geometry={nodes["Node-Mesh002_4"].geometry}
          material={materials.mat25}
        />
      </group>
      <group
        name="Node001"
        position={[-3.244, 1.378, 1.941]}
        rotation={[0, -1.566, 0]}
        scale={0.713}
      >
        <mesh
          name="Node-Mesh006"
          geometry={nodes["Node-Mesh006"].geometry}
          material={materials["mat23.002"]}
        />
        <mesh
          name="Node-Mesh006_1"
          geometry={nodes["Node-Mesh006_1"].geometry}
          material={materials["mat21.002"]}
        />
        <mesh
          name="Node-Mesh006_2"
          geometry={nodes["Node-Mesh006_2"].geometry}
          material={materials["mat15.002"]}
        />
        <mesh
          name="Node-Mesh006_3"
          geometry={nodes["Node-Mesh006_3"].geometry}
          material={materials["mat24.002"]}
        />
        <mesh
          name="Node-Mesh006_4"
          geometry={nodes["Node-Mesh006_4"].geometry}
          material={materials["mat25.001"]}
        />
      </group>
      <group
        name="Node002"
        position={[-3.244, 2.001, 2.286]}
        rotation={[1.572, -1.566, 0]}
        scale={0.713}
      >
        <mesh
          name="Node-Mesh007"
          geometry={nodes["Node-Mesh007"].geometry}
          material={materials["mat23.003"]}
        />
        <mesh
          name="Node-Mesh007_1"
          geometry={nodes["Node-Mesh007_1"].geometry}
          material={materials["mat21.003"]}
        />
        <mesh
          name="Node-Mesh007_2"
          geometry={nodes["Node-Mesh007_2"].geometry}
          material={materials["mat15.003"]}
        />
        <mesh
          name="Node-Mesh007_3"
          geometry={nodes["Node-Mesh007_3"].geometry}
          material={materials["mat24.003"]}
        />
        <mesh
          name="Node-Mesh007_4"
          geometry={nodes["Node-Mesh007_4"].geometry}
          material={materials["mat25.002"]}
        />
      </group>
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={materials["Material.007"]}
      />
    </group>
  );
}

useGLTF.preload("models/scene.gltf");
